export const STORE_OBJECT_LOAD_SUCCESSFUL = "STORE_OBJECT_LOAD_SUCCESSFUL";
export const STORE_OBJECT_LOAD_FAILED = "STORE_OBJECT_LOAD_FAILED";
export const STORE_CREATE_OBJECT = "STORE_CREATE_OBJECT";
export const STORE_LOAD_OBJECT = "STORE_LOAD_OBJECT";
export const STORE_OBJECT_CHANGED = "STORE_OBJECT_CHANGED";
